@rootURL = http://localhost:5299

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/5
Accept: application/json
###
POST {{rootURL}}/api/books/
Content-Type: application/json
{
    "title": "C# Unlocked",
    "author": "Alen",
    "yearPublished": 2024
}
###
PUT {{rootURL}}/api/books/10
Content-Type: application/json
{
    "id": 10,
    "title": "C# Unlocked",
    "author": "Alen",
    "yearPublished": 2024
}
###
DELETE {{rootURL}}/api/books/9